### ISSUE TITLE
MultiLCA checklist

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2-calc#86]
- [x] Finish #79 with tests
- [x] Add tests for `SparseMatrixDict`
- [x] Release new version of `matrix_utils`
- [x] Create anaconda recipe for `json_logging`
- [x] Add test for consistent indexing using arrays
- [x] Add code for loading normalization and weighting data
- [x] Add code for using `MethodConfig` when using normalization or weighting
- [x] Add flow-specific normalization code and tests
- [x] Add IC-specific weighting code and tests
- [x] Add normalization-specific weighting code and tests
- [x] Test logging on `next`
